server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: paascloud-discovery
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qqqlllei/cloud-config-repo
          username:
          password:
          search-paths: /*
      label: master
info:
  owner: paascloud.net@gmail.com
  version: 1.0-SNAPSHOT

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@10.33.80.114:8761/eureka/
    instance:
      instance-id: ${spring.cloud.client.ipAddress}:${server.port} #通过ip指定链接地址
  instance:
    prefer-ip-address: true #必须设置为true

security: # 配置中心的用户名密码
  basic:
    enabled: ${security.basic.enabled:true}
  user:
    name: ${security.user.name:admin}
    password: ${security.user.password:admin}
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log


